name: ci

on:
  push:
  pull_request:
    branches:
      - 'master'
      - 'main'

env:
  TEST_TAG: tugraph/tugraph-ut:test
  CODECOV_TOKEN: b67f87a8-ffd6-49be-81eb-c5bc17dea676

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Unit Test
        uses: docker/build-push-action@v3
        with:
          file: ci/gh-actions/ubuntu-latest/Dockerfile
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
