name: ci

on:
  push:
  pull_request:
    branches:
      - '*'

env:
  TEST_TAG: tugraph/tugraph-ut:test

# 1. Seems GitHub limits the output passed among jobs up to 1MB,
#    so we can't break down the entire workflow to multi-jobs.
# 2. Since we have submodules in repo, the git binary in docker image
#    should be upgrade to at least 2.18 in order to use actions/checkout@v3
#    inside docker instead of running ut, it via Dockerfile
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Unit Test
        uses: docker/build-push-action@v3
        with:
          file: ci/gh-actions/ubuntu-latest/Dockerfile
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
          secrets: |
            "CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}"
